fix(download-llvm): support tags without 'v' or 'version_' prefix (#64)
The llvm-project releases are not prefixed with 'v' or 'version' and
so we need to relax the check:
```
❯ wasixccenv download-llvm 21.1.204
error: invalid value '21.1.204' for '[TAG]': Invalid tag specification: `21.1.204`. Use 'latest', a tag starting with 'v', or 'version_XXX'.
``